### ISSUE TITLE
Does readme need some changes?

### ISSUE THREAD

**Issue by rgleason** [marcobergman/ais_simulation#11]
prerequisites:

    python 2 or 3 installed with wxpython (install with pip install -U wxPython)
    udp clients listening to broadcasts (0.0.0.0) on socket 10111, or
    some nmea listener listening on localhost tcp/20220 (change the code for this)

**Comment by marcobergman** [comment]
You seem to have and old readme; it listens out on 10110 nowadays. I used 10111 in the past to coexist with a default signalk install.

**Comment by rgleason** [comment]
Thanks
