### ISSUE TITLE
test

### ISSUE THREAD

**Issue by marcobergman** [marcobergman/ais_simulation#8]
![image](https://user-images.githubusercontent.com/17980560/152997900-49a85325-de57-4238-b3f3-eda283a0aab1.png)

**Comment by rgleason** [comment]
Marco, what is this testing? Looks pretty interesting.

**Comment by marcobergman** [comment]
oh sorry I misuse github for photo storage. If you create an issue and paste an image, you get an eternal url, even in you don't save the issue. I inadvertently saved this one. This is some surveyors sounding that I converted into a kap file.

**Comment by rgleason** [comment]
Interesting. Thanks.

**Comment by rgleason** [comment]
Marco, you are the only one who can close this.

**Comment by marcobergman** [comment]
Another one ;-)

![image](https://user-images.githubusercontent.com/17980560/213015333-b93e3d98-c627-4d11-af65-88f70450b19d.png)
